steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', './cmd/daemon/daemon', './cmd/daemon/daemon.go']
  env:
  - 'PROJECT_ROOT=github.com/blackducksoftware/perceptor-skyfire'
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'
  - 'GOARCH=amd64'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blackducksoftware/skyfire-daemon:$BRANCH_NAME', './cmd/daemon/.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blackducksoftware/skyfire-daemon:$BRANCH_NAME']
