apiVersion: v1
kind: Pod
metadata:
  name: addpodfromfile-ibmjava
  namespace: kubedeployments
spec:
  containers:
  - image: ibmjava:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: ibmjava
  restartPolicy: Always
